// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOz-XjeNahZRVrYE-y44H4vDka-iJHD0k',
    appId: '1:556490183378:web:dfffd8fa807bba5bed130b',
    messagingSenderId: '556490183378',
    projectId: 'flutterlessons-6d28f',
    authDomain: 'flutterlessons-6d28f.firebaseapp.com',
    storageBucket: 'flutterlessons-6d28f.appspot.com',
    measurementId: 'G-F6LD4WHT09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3-UaQHdz9n_2m8LvY2y0OQU3JdVTXKak',
    appId: '1:556490183378:android:36964d617b08d4b2ed130b',
    messagingSenderId: '556490183378',
    projectId: 'flutterlessons-6d28f',
    storageBucket: 'flutterlessons-6d28f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL4sugYBlXMSLc5DUGNXRIKxfNglWK1P0',
    appId: '1:556490183378:ios:cc69cb77e531b369ed130b',
    messagingSenderId: '556490183378',
    projectId: 'flutterlessons-6d28f',
    storageBucket: 'flutterlessons-6d28f.appspot.com',
    iosClientId: '556490183378-td9vp0s7p27uph7v87pihhe9k3jnne07.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutternew',
  );
}
